language: go
go:
  - 1.7

services:
  - docker

before_install:
  # checking that build.sh works but testing bucketftp in a different container
  - bash -x build.sh
  - docker build -f Dockerfile.testing -t bucketftp_testing .

install: true

script: docker run 
  -e "FTP_PORT=$FTP_PORT"
  -e "AWS_REGION=$AWS_REGION"
  -e "S3_BUCKET_NAME=$S3_BUCKET_NAME"
  -e "FTP_USER=$FTP_USER"
  -e "FTP_PASSWD=$FTP_PASSWD"
  -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
  -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
  -t bucketftp_testing

#deploy:
#   - provider: script
#     skip_cleanup: true
#     script: ./build-push.sh
#     on:
#       branch: master

env:
    global:
        # Environment variables FTP_PASSWD, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are stored in Travis CIs job config
        - FTP_PORT=3000
        - AWS_REGION=ap-southeast-2
        - S3_BUCKET_NAME=bucketftp-test.geonet.org.nz
        - FTP_USER=ftpuser
