language: go
go:
  - 1.7

services:
  - docker

before_install:
  - bash -x build.sh
  # network=host bypasses a networking conflict when running the FTP server in docker and test FTP client on localhost
  - docker run --network host
      -e "FTP_PORT=$FTP_PORT"
      -e "AWS_REGION=$AWS_REGION"
      -e "S3_BUCKET_NAME=$S3_BUCKET_NAME"
      -e "FTP_USER=$FTP_USER"
      -e "FTP_PASSWD=$FTP_PASSWD"
      -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
      -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
      -d -t bucketftp:latest

# disable go get since we're using govendor
install: true

script: go test -v ./...

#notifications:
#  hipchat:
#    rooms:
#      secure: ""
#    notify: true
#    on_success: always
#    on_failure: always

#deploy:
#   - provider: script
#     skip_cleanup: true
#     script: ./build-push.sh
#     on:
#       branch: master

env:
    global:
        # Environment variables FTP_PASSWD, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are stored in Travis CIs job config
        - FTP_PORT=3000
        - AWS_REGION=ap-southeast-2
        - S3_BUCKET_NAME=bucketftp-test.geonet.org.nz
        - FTP_USER=ftpuser
